name: Install LLVM
description: Installs specific LLVM version
inputs:
  matrix_id:
    required: true
  llvm_version:
    required: true
  llvm_arch:
    required: true
  cached:
    required: false
runs:
  using: composite
  steps:
    - name: Install LLVM
      if: ${{ inputs.matrix_id != 'win' }}
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: ${{ inputs.llvm_version }}
        directory: llvm
        arch: ${{ inputs.llvm_arch }}
        cached: ${{ inputs.cached }}

    - name: Install LLVM (windows)
      if: ${{ inputs.cached != 'true' && inputs.matrix_id == 'win' }}
      shell: bash
      run: |
        set -eux
        version='${{ inputs.llvm_version }}'
        triple='x86_64-pc-windows-msvc'
        curl -fL --retry 3 --max-time 300 -o clang+llvm.tar.xz \
          https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/clang+llvm-$version-$triple.tar.xz

        mkdir llvm
        tar -xf clang+llvm.tar.xz --strip 1 -C llvm --wildcards   \
          '*/bin'                                                 \
          '*/include/llvm'                                        \
          '*/include/llvm-c'                                      \
          '*/lib/*.lib'                                           \
          '*/lib/cmake/llvm/*'                                    \
          '*/lib/clang/*/include/*'                               \
          '*/lib/clang/*/lib/windows/*'
        rm clang+llvm.tar.xz
        sed -i -E 's|C:/Program Files[^/]*/Microsoft Visual Studio/[0-9]+/[^/]+/DIA SDK/lib/amd64/diaguids.lib;||g' llvm/lib/cmake/llvm/LLVMExports.cmake
    
    - name: Set LLVM PATH (windows)
      if: ${{ inputs.matrix_id == 'win' }}
      shell: bash
      run: |
        echo "cached: ${{inputs.cached == true}}"
        echo "$GITHUB_WORKSPACE/llvm/bin" >> $GITHUB_PATH
